import { useEffect, useMemo, useState } from 'react';
import { ArrowLeft, ArrowRight, Check, Compass, EyeOff, Gauge, Layers3, MonitorPlay, Sparkles, TimerReset } from 'lucide-react';
import type { MoodTag, StreamingPlatform, TasteProfile } from '../../types';
import { moods, platforms } from '../../data/mockSeries';
import { runtimeSnapshot, type RuntimeSnapshot } from '../../lib/runtimeStatus';

type Props = { onComplete: (answers: TasteProfile) => void; initialMood?: MoodTag };
const pacing = [{ value: 34, title: 'Yavaş açılan', text: 'Atmosfer ve ayrıntı önce gelir.' },{ value: 62, title: 'Doğal akış', text: 'Dram ve merak dengede kalır.' },{ value: 86, title: 'Hemen içine alan', text: 'Temposu ilk bölümde yakalar.' }];
const complexity = [{ value: 30, title: 'Açık rota', text: 'Takibi kolay, temiz anlatı.' },{ value: 64, title: 'Katmanlı', text: 'Alt metin ve detaylarla büyür.' },{ value: 91, title: 'Teori kurduran', text: 'Zaman, kimlik, gizem ve kurgu.' }];
const sessions: NonNullable<TasteProfile['session']>[] = ['Kısa akşam','Hafta sonu','Uzun maraton'];
const toneOptions: Array<{ label: string; mood: MoodTag; note: string; group: string }> = [
  { label:'Merak',mood:'Zihin Yakan',note:'yeni bir fikir aç',group:'ZİHİN'},{label:'Küçük keşifler',mood:'Konfor/Rahatlatıcı',note:'sır ve atmosfer',group:'ZİHİN'},{label:'Büyük sorular',mood:'Zihin Yakan',note:'teori ve bulmaca',group:'ZİHİN'},{label:'Yeni bir dünya',mood:'Distopya',note:'başka bir düzen',group:'ZİHİN'},
  {label:'Günlük macera',mood:'Yüksek Adrenalin',note:'hayata hareket kat',group:'GERİLİM'},{label:'Teknoloji merakı',mood:'Siberpunk/Teknoloji',note:'gelecek ve etik',group:'GERİLİM'},{label:'Sakin gizem',mood:'Zihin Yakan',note:'ipucu ve atmosfer',group:'GERİLİM'},{label:'Karanlık psikoloji',mood:'Karanlık/Gerilim',note:'takıntı ve çatışma',group:'GERİLİM'},
  {label:'İktidar oyunu',mood:'Politik/Güç',note:'güç ve entrika',group:'İNSAN'},{label:'Tarihi ihtişam',mood:'Politik/Güç',note:'hanedan ve rekabet',group:'İNSAN'},{label:'Hüzünlü',mood:'Melankolik',note:'yavaş ve içe dönük',group:'İNSAN'},{label:'Romantik yoğunluk',mood:'Melankolik',note:'bağlar ve kırılmalar',group:'İNSAN'},
  {label:'Sıcacık',mood:'Konfor/Rahatlatıcı',note:'iyi hissettiren',group:'NEFES'},{label:'Keskin komedi',mood:'Konfor/Rahatlatıcı',note:'hafif ve akıcı',group:'NEFES'},{label:'Aile hikâyesi',mood:'Konfor/Rahatlatıcı',note:'yakın ve tanıdık',group:'NEFES'},{label:'Yüksek tansiyon',mood:'Yüksek Adrenalin',note:'anında akan',group:'NEFES'},{label:'Hayatta kalma',mood:'Yüksek Adrenalin',note:'baskı ve tempo',group:'NEFES'},{label:'Fantastik kaçış',mood:'Distopya',note:'başka dünyalar',group:'NEFES'},
  {label:'Yalnızlık',mood:'Melankolik',note:'sessiz ve içsel',group:'İNSAN'},{label:'Umut',mood:'Konfor/Rahatlatıcı',note:'iyileşme ve bağ',group:'İNSAN'},{label:'Kırılganlık',mood:'Melankolik',note:'duygusal yakınlık',group:'İNSAN'},{label:'İntikam',mood:'Karanlık/Gerilim',note:'hesaplaşma ve öfke',group:'İNSAN'},
  {label:'Kozmik merak',mood:'Zihin Yakan',note:'bilinmeyen ve evren',group:'ZİHİN'},{label:'Zaman döngüsü',mood:'Zihin Yakan',note:'neden ve sonuç',group:'ZİHİN'},{label:'Güvenilmez anlatıcı',mood:'Zihin Yakan',note:'gerçeklik kayıyor',group:'ZİHİN'},{label:'Bulmaca',mood:'Zihin Yakan',note:'ipucu ve çözüm',group:'ZİHİN'},
  {label:'Hayaletli',mood:'Karanlık/Gerilim',note:'tekinsiz atmosfer',group:'GERİLİM'},{label:'Mahkeme',mood:'Politik/Güç',note:'adalet ve baskı',group:'GERİLİM'},{label:'Casusluk',mood:'Karanlık/Gerilim',note:'gizli kimlikler',group:'GERİLİM'},{label:'Sistem karşıtı',mood:'Siberpunk/Teknoloji',note:'kurumlara direnç',group:'GERİLİM'},
  {label:'Romantik komedi',mood:'Konfor/Rahatlatıcı',note:'yakınlık ve mizah',group:'NEFES'},{label:'Yolculuk',mood:'Yüksek Adrenalin',note:'hareket ve keşif',group:'NEFES'},{label:'Rekabet',mood:'Yüksek Adrenalin',note:'hırs ve mücadele',group:'NEFES'},{label:'Nostalji',mood:'Melankolik',note:'geçmişe dönüş',group:'NEFES'},
  {label:'Günlük hayat',mood:'Konfor/Rahatlatıcı',note:'tanıdık ve doğal',group:'İNSAN'},{label:'Arkadaşlık',mood:'Konfor/Rahatlatıcı',note:'birlikte büyümek',group:'İNSAN'},{label:'İş hayatı',mood:'Politik/Güç',note:'ekip ve hedefler',group:'İNSAN'},{label:'İlk aşk',mood:'Melankolik',note:'heyecan ve yakınlık',group:'İNSAN'},
  {label:'Keşif',mood:'Zihin Yakan',note:'yeni yerler ve fikirler',group:'ZİHİN'},{label:'Bilim',mood:'Siberpunk/Teknoloji',note:'sorular ve deneyler',group:'ZİHİN'},{label:'Doğa',mood:'Konfor/Rahatlatıcı',note:'yavaş ve ferah',group:'ZİHİN'},{label:'Tarih',mood:'Politik/Güç',note:'geçmiş ve değişim',group:'ZİHİN'},
  {label:'Macera',mood:'Yüksek Adrenalin',note:'hareket ve keşif',group:'GERİLİM'},{label:'Spor',mood:'Yüksek Adrenalin',note:'takım ve mücadele',group:'GERİLİM'},{label:'Gizem',mood:'Zihin Yakan',note:'sakin merak',group:'GERİLİM'},{label:'Komşuluk',mood:'Konfor/Rahatlatıcı',note:'küçük dünya hikâyeleri',group:'GERİLİM'},
];
const steps = [['01','Duygu','Bu akşamın ana hissini seç.'],['02','Enerji','Hikâyenin hızını belirle.'],['03','Derinlik','Anlatının ne kadar katmanlı olacağını söyle.'],['04','Çerçeve','İzleme koşullarını daralt.'],['05','Sınırlar','İstemediğin tonları dışarıda bırak.']] as const;
const statusText = { ready:'çalışıyor',loading:'yükleniyor',standby:'istekte hazırlanır',failed:'erişilemedi' } as const;

export function TasteGuide({ onComplete, initialMood }: Props) {
  const [step,setStep] = useState(0); const [runtime,setRuntime] = useState<RuntimeSnapshot>(()=>runtimeSnapshot());
  const [answers,setAnswers] = useState<Partial<TasteProfile>>({platform:'Tümü',avoidTags:[],keywords:[]}); const [showAllTones,setShowAllTones] = useState(true); const current=steps[step];
  useEffect(()=>{const update=()=>setRuntime(runtimeSnapshot());window.addEventListener('sera-runtime-status',update);return()=>window.removeEventListener('sera-runtime-status',update);},[]);
  useEffect(() => { if (!initialMood || answers.moods?.includes(initialMood)) return; const option = toneOptions.find(item => item.mood === initialMood); if (option) chooseTone(option); }, [initialMood]);
  const canContinue=step===0?Boolean(answers.moods?.length||answers.mood):step===1?Boolean(answers.pacing):step===2?Boolean(answers.complexity):true;
  const selectedTones=answers.keywords?.filter(keyword=>toneOptions.some(tone=>tone.label===keyword))||[];
  const routeSignals=useMemo(()=>[...selectedTones,answers.pacing?`${answers.pacing}/100 tempo`:null,answers.complexity?`${answers.complexity}/100 derinlik`:null,answers.session].filter(Boolean),[selectedTones,answers]);
  const complete=()=>onComplete({mood:answers.mood!,moods:answers.moods,pacing:answers.pacing!,complexity:answers.complexity!,platform:answers.platform||'Tümü',session:answers.session,avoidTags:answers.avoidTags,keywords:answers.keywords});
  const chooseTone=(option:typeof toneOptions[number])=>setAnswers(value=>{
    const picked=(value.keywords||[]).includes(option.label);
    const toneKeywords=(value.keywords||[]).filter(item=>item!==option.label);
    const nextKeywords=picked?toneKeywords:[...toneKeywords,option.label].slice(-10);
    const selectedOptions=toneOptions.filter(tone=>nextKeywords.includes(tone.label));
    const selectedMoods=[...new Set(selectedOptions.map(tone=>tone.mood))];
    return {...value,mood:selectedMoods[0],moods:selectedMoods,keywords:nextKeywords};
  });
  return <section id="taste-guide" className="taste-guide route-builder" aria-labelledby="taste-guide-title">
    <aside className="route-builder-rail"><div className="route-rail-brand"><Compass size={17}/><span>İLK ROTA</span></div><div className="route-rail-steps">{steps.map(([number,label],index)=><button type="button" key={number} className={index===step?'active':index<step?'done':''} disabled={index>step} onClick={()=>setStep(index)}><b>{number}</b><span>{label}</span><i/></button>)}</div><div className="route-live-summary"><small>ROTA SİNYALİ</small>{routeSignals.length?routeSignals.map(item=><span key={String(item)}>{item}</span>):<p>İlk tonu seç; adaylar buna göre daralacak.</p>}</div></aside>
    <div className="route-builder-main"><header className="taste-guide-intro"><div><p className="eyebrow"><Sparkles size={13}/> SÉRA / KİŞİSEL ROTA</p><h2 id="taste-guide-title">Bir kategori değil.<br/><em>Bu akşamın ritmi.</em></h2><p>Beş kısa karar, tüm canlı arşivde dolaşmanın başlangıç noktasını oluşturur. Bu tercihler sadece cihazında kalır.</p></div></header>
      <div className="route-runtime" aria-label="Çalışma durumu"><span><i className={runtime.tmdb}/><b>TMDB canlı akış</b><small>{statusText[runtime.tmdb]}</small></span><span><i className={runtime.semantic}/><b>Çok dilli metin modeli</b><small>{statusText[runtime.semantic]}</small></span><span><i className={runtime.vision}/><b>MobileNet V2 / poster</b><small>{statusText[runtime.vision]}</small></span></div>
      <div className="route-step-meter"><span>{current[0]} / 05</span><i><b style={{width:`${(step+1)/5*100}%`}}/></i><small>{current[1]}</small></div>
      <section className="guide-question"><span>{current[0]} / {current[1]}</span><h3>{current[2]}</h3>
        {step===0&&<><p className="tone-multi-note">Kendine yakın hisleri seçebilirsin. 46 sinyal arasından en fazla 10 tanesi rotanın ortak profilini oluşturur; daha çok sinyal, daha isabetli kişiselleştirme demektir.</p><div className="tone-groups" onWheelCapture={event => { const panel = event.currentTarget as HTMLElement; const target = event.target as HTMLElement; const group = target.closest('section')?.querySelector('div'); if (group && group.scrollHeight > group.clientHeight) { group.scrollTop += event.deltaY; event.stopPropagation(); panel.scrollTop += event.deltaY * .2; } }} >{[['ZİHİN','MERAK'],['GERİLİM','ENERJİ'],['İNSAN','DUYGU'],['NEFES','DÜNYA']].map(([group,label])=><section key={group}><p>{label}</p><div>{toneOptions.filter(option=>option.group===group).filter((option,index)=>showAllTones || index < 2 || selectedTones.includes(option.label)).map(option=>{const picked=selectedTones.includes(option.label);return <button type="button" key={option.label} onClick={()=>chooseTone(option)} className={picked?'picked':''}>{picked&&<Check size={14}/>}<b>{option.label}</b><small>{option.note}</small></button>})}</div></section>)}</div><button className="tone-expand" type="button" onClick={()=>setShowAllTones(value=>!value)}>{showAllTones?'Temel seçeneklere dön':'Tüm tonları göster'}</button></>}
        {step===1&&<div className="guide-options choice-cards">{pacing.map(option=><button key={option.value} onClick={()=>setAnswers(value=>({...value,pacing:option.value}))} className={answers.pacing===option.value?'picked':''}><Gauge size={18}/><b>{option.title}</b><small>{option.text}</small></button>)}</div>}
        {step===2&&<div className="guide-options choice-cards">{complexity.map(option=><button key={option.value} onClick={()=>setAnswers(value=>({...value,complexity:option.value}))} className={answers.complexity===option.value?'picked':''}><Layers3 size={18}/><b>{option.title}</b><small>{option.text}</small></button>)}</div>}
        {step===3&&<div className="route-builder-frame"><div className="guide-options session-options">{sessions.map(session=><button key={session} className={answers.session===session?'picked':''} onClick={()=>setAnswers(value=>({...value,session}))}><TimerReset size={17}/><b>{session}</b><small>{session==='Kısa akşam'?'Tek oturumluk güçlü seçimler.':session==='Hafta sonu'?'Birkaç bölümlük dengeli rota.':'Uzun soluklu dünyalar.'}</small></button>)}</div><label className="guide-platform"><span><MonitorPlay size={15}/> Varsa öncelikli platform</span><select value={answers.platform} onChange={event=>setAnswers(value=>({...value,platform:event.target.value as StreamingPlatform|'Tümü'}))}>{(['Tümü',...platforms] as const).map(platform=><option key={platform}>{platform}</option>)}</select></label></div>}
        {step===4&&<div className="route-builder-frame"><p className="route-hint"><EyeOff size={16}/> İstemediğin tonları dışarıda bırak; rota bu sinyalleri azaltacak.</p><div className="guide-options mood-options avoid-options">{moods.filter(mood=>!answers.moods?.includes(mood)).map(mood=>{const picked=answers.avoidTags?.includes(mood);return <button key={mood} onClick={()=>setAnswers(value=>({...value,avoidTags:picked?(value.avoidTags||[]).filter(tag=>tag!==mood):[...(value.avoidTags||[]),mood]}))} className={picked?'picked':''}>{picked&&<Check size={14}/>} {mood}</button>})}</div><label className="route-keyword"><span>Bir sahne, ton veya anahtar kelime ekle</span><input placeholder="Örn. küçük kasaba gizemi, düşman kardeşler…" onKeyDown={event=>{if(event.key==='Enter'){event.preventDefault();const value=event.currentTarget.value.trim();if(value)setAnswers(current=>({...current,keywords:[...(current.keywords||[]),value].slice(0,8)}));event.currentTarget.value='';}}}/></label>{Boolean(answers.keywords?.length)&&<div className="route-keywords">{answers.keywords?.filter(item=>!selectedTones.includes(item)).map(keyword=><span key={keyword}>{keyword}<button onClick={()=>setAnswers(value=>({...value,keywords:value.keywords?.filter(item=>item!==keyword)}))}>×</button></span>)}</div>}</div>}
      </section>
      <footer className="guide-footer"><button className="guide-back" onClick={()=>setStep(value=>Math.max(0,value-1))} disabled={step===0}><ArrowLeft size={16}/> Geri</button><button className="guide-next" onClick={()=>step===4?complete():setStep(value=>value+1)} disabled={!canContinue}>{step===4?<>Canlı rotayı aç <Sparkles size={16}/></>:<>Devam <ArrowRight size={16}/></>}</button></footer>
    </div>
  </section>;
}
