import { Compass, Gauge, Layers3, MapPinned, Pencil, Plus, RotateCcw, X } from 'lucide-react';
import { useMemo, useState } from 'react';
import type { MoodTag, TasteProfile, TVSeries, WatchState } from '../../types';

type Props = { profile: TasteProfile; items: TVSeries[]; watchStates: Map<string,WatchState>; onWatchState: (series:TVSeries,state:WatchState) => void; onReset: () => void; onExplore: () => void; onUpdate: (profile: TasteProfile) => void };
const pace = (value:number) => value < 42 ? 'Sakin ve atmosferik' : value > 74 ? 'Hızlı ve hareketli' : 'Dengeli akış';
const depth = (value:number) => value < 42 ? 'Rahat takip' : value > 74 ? 'Katmanlı kurgu' : 'Orta yoğunluk';
const avoidable: MoodTag[]=['Karanlık/Gerilim','Yüksek Adrenalin','Melankolik','Zihin Yakan'];

export function RouteProfile({ profile, items, watchStates, onWatchState, onReset, onExplore, onUpdate }: Props) {
  const [editing,setEditing]=useState(false); const [seriesQuery,setSeriesQuery]=useState(''); const [keyword,setKeyword]=useState('');
  const references=profile.referenceTitles||[]; const keywords=profile.keywords||[]; const avoids=profile.avoidTags||[];
  const suggestions=useMemo(()=>items.filter(item=>seriesQuery.length>1&&!references.includes(item.title)&&item.title.toLocaleLowerCase('tr-TR').includes(seriesQuery.toLocaleLowerCase('tr-TR'))).slice(0,5),[items,seriesQuery,references]);
  const save=(next:Partial<TasteProfile>)=>onUpdate({...profile,...next});
  const sharedSignals=(titles:string[])=>{const selected=items.filter(value=>titles.includes(value.title));const pool=selected.flatMap(value=>[...value.genres,...value.moodTags]);return [...new Set(pool.filter(signal=>selected.length===1||selected.every(value=>[...value.genres,...value.moodTags].includes(signal))))];};
  const addReference=(item:TVSeries)=>{if(references.length>=10)return;const next=[...references,item.title];save({referenceTitles:next,referenceSignals:sharedSignals(next)});setSeriesQuery('');};
  const removeReference=(title:string)=>{const next=references.filter(value=>value!==title);save({referenceTitles:next,referenceSignals:sharedSignals(next)});};
  const addKeyword=()=>{const value=keyword.trim();if(!value||keywords.includes(value))return;save({keywords:[...keywords,value].slice(0,8)});setKeyword('');};
  return <section className="route-profile" aria-labelledby="route-profile-title">
    <div className="route-profile-intro"><span className="route-profile-mark"><MapPinned size={18}/></span><div><p className="eyebrow">AKTİF İZLEME ROTASI</p><h2 id="route-profile-title">Bu rotada ne aradığın net.</h2><p>Temel tonun yanında referans dizilerin, kendi kelimelerin ve kaçınmak istediklerin de sırayı etkiler.</p></div></div>
    <div className="route-profile-signals"><article><Compass size={16}/><small>ANA TON</small><b>{profile.mood}</b><i><em style={{width:'82%'}}/></i></article><article><Gauge size={16}/><small>TEMPO</small><b>{pace(profile.pacing)}</b><i><em style={{width:`${profile.pacing}%`}}/></i></article><article><Layers3 size={16}/><small>ANLATI</small><b>{depth(profile.complexity)}</b><i><em style={{width:`${profile.complexity}%`}}/></i></article></div>
    <div className="route-profile-summary"><span>{references.length}/10 referans dizi</span><span>{keywords.length} anahtar kelime</span><span>{profile.session||'İzleme bağlamı serbest'}</span></div>
    {editing&&<div className="route-editor"><div className="route-editor-head"><b>Rotanı derinleştir</b><small>En fazla 10 dizi ve 8 anahtar kelime. İzledim/Listeme sinyalleri kişisel öneriyi günceller.</small></div><label className="route-editor-label">İzlediğin veya sevdiğin diziler <div className="route-editor-input"><input value={seriesQuery} onChange={event=>setSeriesQuery(event.target.value)} placeholder="Örn. Dark, The Bear, Sherlock…"/><button type="button" aria-label="Dizi referansı ekle"><Plus size={15}/></button></div></label>{suggestions.length>0&&<div className="route-reference-results">{suggestions.map(item=><button type="button" key={item.id} onClick={()=>addReference(item)}><img src={item.posterUrl} alt=""/><span><b>{item.title}</b><small>{item.genres.slice(0,2).join(' · ')}</small></span><Plus size={15}/></button>)}</div>}<div className="route-reference-statuses">{references.map(title=>{const item=items.find(series=>series.title===title);const state=item?watchStates.get(item.id):undefined;return <article key={title}><span>{item?.posterUrl&&<img src={item.posterUrl} alt=""/>}<b>{title}</b></span><div>{item&&<button type="button" className={state==='plan'?'active':''} onClick={()=>onWatchState(item,'plan')}>Listeme</button>}{item&&<button type="button" className={state==='completed'?'active':''} onClick={()=>onWatchState(item,'completed')}>İzledim</button>}<button type="button" aria-label={`${title} referansını kaldır`} onClick={()=>removeReference(title)}><X size={12}/></button></div></article>})}</div><label className="route-editor-label">Aradığın atmosfer, tema veya hikâye unsurları <div className="route-editor-input"><input value={keyword} onChange={event=>setKeyword(event.target.value)} onKeyDown={event=>{if(event.key==='Enter'){event.preventDefault();addKeyword();}}} placeholder="Örn. zaman döngüsü, zeki diyalog…"/><button type="button" aria-label="Anahtar kelime ekle" onClick={addKeyword}><Plus size={15}/></button></div></label><div className="route-tags route-keywords">{keywords.map(value=><span key={value}>{value}<button type="button" aria-label={`${value} anahtar kelimesini kaldır`} onClick={()=>save({keywords:keywords.filter(item=>item!==value)})}><X size={12}/></button></span>)}</div><div className="route-editor-label">Bu rotada az görmek istediklerin <div className="route-avoid-grid">{avoidable.map(tag=><button type="button" key={tag} className={avoids.includes(tag)?'selected':''} onClick={()=>save({avoidTags:avoids.includes(tag)?avoids.filter(value=>value!==tag):[...avoids,tag]})}>{tag}</button>)}</div></div><label className="route-editor-label">Bu rota ne için? <select value={profile.session||''} onChange={event=>save({session:(event.target.value||undefined) as TasteProfile['session']})}><option value="">Serbest keşif</option><option>Kısa akşam</option><option>Hafta sonu</option><option>Uzun maraton</option></select></label></div>}
    <div className="route-profile-actions"><button type="button" onClick={onExplore}>Rotayı incele</button><button type="button" onClick={()=>setEditing(value=>!value)}><Pencil size={14}/>{editing?'Düzenlemeyi kapat':'Rotayı derinleştir'}</button><button type="button" onClick={onReset}><RotateCcw size={14}/> Rotayı yeniden kur</button></div>
  </section>;
}
